### ISSUE TITLE
'utf-8' codec can't decode byte 

### ISSUE THREAD

**Issue by yondu22** [Morizeyao/GPT2-Chinese#124]
```
 python generate_texts.py --model_path model/pytorch_model.bin --tokenizer_path model/vocab.txt --model_config model/config.json 
args:
Namespace(articles_per_title=5, device='0,1,2,3', length=-1, model_config='model/config.json', model_path='model/pytorch_model.bin', no_wordpiece=False, repetition_penalty=1.0, save_path='generated/', segment=False, temperature=1, titles='萧炎', titles_file='', tokenizer_path='model/vocab.txt', topk=8, topp=0)
Traceback (most recent call last):
  File "generate_texts.py", line 186, in <module>
    main()
  File "generate_texts.py", line 139, in main
    model = GPT2LMHeadModel.from_pretrained(args.model_path)
  File "/opt/conda/lib/python3.6/site-packages/transformers/modeling_utils.py", line 287, in from_pretrained
    **kwargs
  File "/opt/conda/lib/python3.6/site-packages/transformers/configuration_utils.py", line 154, in from_pretrained
    config = cls.from_json_file(resolved_config_file)
  File "/opt/conda/lib/python3.6/site-packages/transformers/configuration_utils.py", line 186, in from_json_file
    text = reader.read()
  File "/opt/conda/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

**Comment by yondu22** [comment]
The final solution is that the model address points to a directory rather than a file name.

**Comment by songwanguw** [comment]
what do you mean?
