### ISSUE TITLE
在使用作者提供的散文预训练模型的时候，出现了utf8问题

### ISSUE THREAD

**Issue by justin0314** [Morizeyao/GPT2-Chinese#135]
Traceback (most recent call last):
  File "e:\GPT2\GPT2-Chinese\train.py", line 251, in <module>
    main()
  File "e:\GPT2\GPT2-Chinese\train.py", line 124, in main
    model = transformers.modeling_gpt2.GPT2LMHeadModel.from_pretrained(args.pretrained_model)
  File "E:\python3.6.6\lib\site-packages\transformers\modeling_utils.py", line 287, in from_pretrained
    **kwargs
  File "E:\python3.6.6\lib\site-packages\transformers\configuration_utils.py", line 154, in from_pretrained
    config = cls.from_json_file(resolved_config_file)
  File "E:\python3.6.6\lib\site-packages\transformers\configuration_utils.py", line 186, in from_json_file
    text = reader.read()
  File "E:\python3.6.6\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

以上是报错信息，是否是因为模型bin文件不是utf-8编码所导致的？但是不知能否将bin文件作编码转换？请教各位！

**Comment by yunpeng01** [comment]
请问这个问题怎么解决的呢？

**Comment by canyousayyes** [comment]
可能是 `--model_path` 出錯，要寫資料夾的路徑而非檔案路徑。
例如用 `--model_path path/to/model/pytorch_model.bin` 會出現上述錯誤，應該寫成 `--model_path path/to/model/`。
