### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by Alimo1029** [Morizeyao/GPT2-Chinese#156]
PS D:\GPT2\GPT2-Chinese-master> python .\train.py --raw
args:
Namespace(batch_size=8, bpe_token=False, device='0,1,2,3', encoder_json='tokenizations/encoder.json', epochs=5, fp16=False, fp16_opt_level='O1', gradient_accumulation=1, log_step=1, lr=0.00015, max_grad_norm=1.0, min_length=128, model_config='config/model_config_small.json', num_pieces=100, output_dir='model/', pretrained_model='', raw=True, raw_data_path='data/train.json', segment=False, stride=768, tokenized_data_path='data/tokenized/', tokenizer_path='cache/vocab_small.txt', vocab_bpe='tokenizations/vocab.bpe', warmup_steps=2000, writer_dir='tensorboard_summary/')
config:
{
  "activation_function": "gelu_new",
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_layer": 10,
  "n_positions": 1024,
  "resid_pdrop": 0.1,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "vocab_size": 13317
}

Traceback (most recent call last):
  File ".\train.py", line 251, in <module>
    main()
  File ".\train.py", line 89, in main
    full_tokenizer.max_len = 999999
AttributeError: can't set attribute

**Comment by Alimo1029** [comment]
My GPU is AMD

**Comment by Alimo1029** [comment]
I delete this code
It's done.
