### ISSUE TITLE
请问运行train_single.py --raw为什么会报错 AttributeError: can't set attribute

### ISSUE THREAD

**Issue by drizzt00s** [Morizeyao/GPT2-Chinese#163]
大佬看下 谢谢

E:\s2\GPT2-Chinese-master>train_single.py --raw
2020-08-16 13:48:38.350959: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-08-16 13:48:38.355713: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
args:
Namespace(batch_size=8, device='0,1,2,3', epochs=5, fp16=False, fp16_opt_level='O1', gradient_accumulation=1, log_step=1, lr=0.00015, max_grad_norm=1.0, model_config='config/model_config_small.json', num_pieces=100, output_dir='model/', pretrained_model='', raw=True, raw_data_path='data/train.json', segment=False, stride=768, tokenized_data_path='data/tokenized/', tokenizer_path='cache/vocab_small.txt', warmup_steps=2000)
config:
{
  "activation_function": "gelu_new",
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_layer": 10,
  "n_positions": 1024,
  "resid_pdrop": 0.1,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "vocab_size": 13317
}

Traceback (most recent call last):
  File "E:\s2\GPT2-Chinese-master\train_single.py", line 227, in <module>
    main()
  File "E:\s2\GPT2-Chinese-master\train_single.py", line 77, in main
    full_tokenizer.max_len = 999999
AttributeError: can't set attribute

**Comment by Luoyingfeng8** [comment]
@drizzt00s 这个直接把full_tokenizer.max_len = 999999注释掉就行了，应该不影响

**Comment by drizzt00s** [comment]
transformer 版本不对

**Comment by zeze813** [comment]
可恶的transformer
