### ISSUE TITLE
最长只能生成1023个字，多了就会出错

### ISSUE THREAD

**Issue by libralibra** [Morizeyao/GPT2-Chinese#199]
报错信息如下，有什么办法能增加这个长度吗？
```
 51%|█████████████████████████▌                        | 1023/2000 [00:13<00:13, 74.78it/s]
Traceback (most recent call last):
  File "generate.py", line 251, in <module>
    main()
  File "generate.py", line 207, in main
    out = generate(
  File "generate.py", line 125, in generate
    return fast_sample_sequence(model, context, length, temperature=temperature, top_k=top_k, top_p=top_p,
  File "generate.py", line 109, in fast_sample_sequence
    output = model(prev, past=past)
  File "C:\Program Files\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\transformers\modeling_gpt2.py", line 528, in forward
    transformer_outputs = self.transformer(input_ids,
  File "C:\Program Files\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\transformers\modeling_gpt2.py", line 438, in forward
    outputs = block(hidden_states,
  File "C:\Program Files\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\transformers\modeling_gpt2.py", line 228, in forward
    output_attn = self.attn(self.ln_1(x),
  File "C:\Program Files\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\transformers\modeling_gpt2.py", line 192, in forward
    attn_outputs = self._attn(query, key, value, attention_mask, head_mask)
  File "C:\Program Files\Python38\lib\site-packages\transformers\modeling_gpt2.py", line 149, in _attn
    w = w * b - 1e4 * (1 - b)
RuntimeError: The size of tensor a (1025) must match the size of tensor b (1024) at non-singleton dimension 3
```

**Comment by 54huige** [comment]
解决了吗 我也有这问题

**Comment by Biaocsu** [comment]
@54huige 你好，这个维度问题你解决了吗？我也碰到了。另外你有好的思路来解决生成文本速度过慢问题吗？

**Comment by 54huige** [comment]
@Biaocsu 没解决 这个index不知道怎么改才行，生成的不慢啊，你用GPU了吗

**Comment by Biaocsu** [comment]
@54huige 我这边使用GPU了
如果不用fast模式，生成一段话要 1分钟，这种模式不会出现上面维度问题
如果使用fast模式，必须将length限制下，这样就不会出现上面维度报错问题，但是同样的输入string，生成时间也要3秒，这延迟太久项目中肯定不行

**Comment by Biaocsu** [comment]
@54huige 你能说下你那边输入长度多少，输出长度大概多少，测试的生成文本时间吗？

**Comment by 54huige** [comment]
@Biaocsu 1023个字 需要1分钟 使用的cpu

**Comment by Biaocsu** [comment]
@54huige 可以测试下GPU吗？我这边项目要求延迟在ms级别，如果真的达不到，需要考虑换模型了。
另外，你知道其他效果相对还可以、速度快的方法吗？多谢

**Comment by liangcaihua** [comment]
> 

ms级别应该不可能吧,  我生二百字也得个1秒

**Comment by liangcaihua** [comment]
> 

3090 生成1024个字需要6秒

**Comment by Biaocsu** [comment]
> > 
> 
> ms级别应该不可能吧, 我生二百字也得个1秒

短句子生成（30个字左右），毫秒级别还是没问题的，我这边后来调到 “几百毫秒”了，现在在用tensorrt进行优化，应该可以达到要求
