### ISSUE TITLE
使用作者给的gpt2通用模型报错

### ISSUE THREAD

**Issue by zhaokanghuiasd** [Morizeyao/GPT2-Chinese#204]
Namespace(batch_size=1, device='0,1,2,3', fast_pattern=True, length=50, model_config='config/config.json', model_path='model/pytorch_model.bin', no_wordpiece=False, nsamples=4, prefix='天气', repetition_penalty=1.0, save_samples=
True, save_samples_path='./sample', segment=False, temperature=1, tokenizer_path='cache/vocab.txt', topk=8, topp=0)
Traceback (most recent call last):
  File "./generate.py", line 222, in <module>
    main()
  File "./generate.py", line 165, in main
    model = GPT2LMHeadModel.from_pretrained(args.model_path)
  File "D:\learning\GPT2-Chinese-master\venv\lib\site-packages\transformers\modeling_utils.py", line 287, in from_pretrained
    **kwargs
  File "D:\learning\GPT2-Chinese-master\venv\lib\site-packages\transformers\configuration_utils.py", line 154, in from_pretrained
    config = cls.from_json_file(resolved_config_file)
  File "D:\learning\GPT2-Chinese-master\venv\lib\site-packages\transformers\configuration_utils.py", line 186, in from_json_file
    text = reader.read()
  File "D:\anaconda\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

**Comment by zhaokanghuiasd** [comment]
改一下参数：parser.add_argument('--model_path', default='model/', type=str, required=False, help='模型路径')
将config.json放在model文件夹下即可
