### ISSUE TITLE
直接运行train.py出现错误You requested GPUs: {gpus}\n But your machine only has: {all_available_gpus}

### ISSUE THREAD

**Issue by 1727949032a** [Morizeyao/GPT2-Chinese#211]
python版本:  3.6
错误信息:
Traceback (most recent call last):
  File "D:/files/python/code/gpt2/GPT2-Chinese/train.py", line 216, in <module>
    precision=32,
  File "D:\files\python\code\gpt2\GPT2-Chinese\venv\lib\site-packages\pytorch_lightning\trainer\connectors\env_vars_connector.py", line 40, in insert_env_defaults
    return fn(self, **kwargs)
  File "D:\files\python\code\gpt2\GPT2-Chinese\venv\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 321, in __init__
    replace_sampler_ddp, deterministic, precision, amp_backend, amp_level, plugins
  File "D:\files\python\code\gpt2\GPT2-Chinese\venv\lib\site-packages\pytorch_lightning\trainer\connectors\accelerator_connector.py", line 129, in __init__
    self.parallel_device_ids = device_parser.parse_gpu_ids(self.gpus)
  File "D:\files\python\code\gpt2\GPT2-Chinese\venv\lib\site-packages\pytorch_lightning\utilities\device_parser.py", line 81, in parse_gpu_ids
    gpus = _sanitize_gpu_ids(gpus)
  File "D:\files\python\code\gpt2\GPT2-Chinese\venv\lib\site-packages\pytorch_lightning\utilities\device_parser.py", line 150, in _sanitize_gpu_ids
    f"You requested GPUs: {gpus}\n But your machine only has: {all_available_gpus}"
pytorch_lightning.utilities.exceptions.MisconfigurationException: You requested GPUs: [0]
 But your machine only has: []

**Comment by JHR0717** [comment]
可以看看你的torch是不是下载的gpu版本？
