### ISSUE TITLE
按照文章步骤运行train时出现了以下状况No such file or directory: 'data/tokenized/tokenized_train_0.txt'

### ISSUE THREAD

**Issue by TralMac** [Morizeyao/GPT2-Chinese#227]
将斗破苍穹整本语料改名为train.json后放入data文件夹，运行train_single.py报错
Traceback (most recent call last):
  File "C:/Users/qb/Desktop/GPT2-Chinese/train_single.py", line 227, in <module>
    main()
  File "C:/Users/qb/Desktop/GPT2-Chinese/train_single.py", line 113, in main
    with open(tokenized_data_path + 'tokenized_train_{}.txt'.format(i), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/tokenized/tokenized_train_0.txt'

**Comment by Escaflowne1985** [comment]
需要在data目录下创建tokenized文件夹，然后第一次train 需要 --raw 参数。

**Comment by cywjava** [comment]
训练 时，加上--raw 会重新创建这些文件
