### ISSUE TITLE
Fail to run train_single

### ISSUE THREAD

**Issue by diansheng** [Morizeyao/GPT2-Chinese#35]
Great repo. However, the train_single script seems to be broken. 

```Traceback (most recent call last):
  File "train_single.py", line 223, in <module>
    main()
  File "train_single.py", line 74, in main
    full_tokenizer = tokenization_bert.BertTokenizer(vocab_file=args.tokenizer_path)
UnboundLocalError: local variable 'tokenization_bert' referenced before assignment
```

**Comment by Morizeyao** [comment]
let me solve this.
