### ISSUE TITLE
用CPU执行train_single训练，报这个错误RuntimeError: index out of range

### ISSUE THREAD

**Issue by leedaga** [Morizeyao/GPT2-Chinese#39]
now time: 9:22. Step 4 of piece 20 of epoch 1, loss 7.352459907531738
Traceback (most recent call last):
  File "c:\Users\LeeDaga\.vscode\extensions\ms-python.python-2019.8.30787\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\LeeDaga\.vscode\extensions\ms-python.python-2019.8.30787\pythonFiles\lib\python\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\LeeDaga\.vscode\extensions\ms-python.python-2019.8.30787\pythonFiles\lib\python\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\LeeDaga\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\LeeDaga\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\LeeDaga\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\GPT2CN\train_single.py", line 224, in <module>
    main()
  File "d:\GPT2CN\train_single.py", line 166, in main
    outputs = model.forward(input_ids=batch_inputs, labels=batch_labels)
  File "C:\Users\LeeDaga\Anaconda3\lib\site-packages\pytorch_transformers\modeling_gpt2.py", line 593, in forward
    past=past, head_mask=head_mask)
  File "C:\Users\LeeDaga\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\LeeDaga\Anaconda3\lib\site-packages\pytorch_transformers\modeling_gpt2.py", line 495, in forward
    inputs_embeds = self.wte(input_ids)
  File "C:\Users\LeeDaga\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\LeeDaga\Anaconda3\lib\site-packages\torch\nn\modules\sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "C:\Users\LeeDaga\Anaconda3\lib\site-packages\torch\nn\functional.py", line 1467, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range: Tried to access index 13411 out of table with 13316 rows. at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensorEvenMoreMath.cpp:237

-------------------------------
换了训练数据也不行

**Comment by Morizeyao** [comment]
你看一下，你所选用的词表大小和你选用的config文件内的词表大小设置分别是多少？

**Comment by leedaga** [comment]
我懂了，第一次学习，感谢指导
