### ISSUE TITLE
生成文本出现编码问题

### ISSUE THREAD

**Issue by ShengXiaoXiao** [Morizeyao/GPT2-Chinese#85]
Traceback (most recent call last):
  File "E:/workspace/code/GPT2-Chinese-master/generate.py", line 226, in <module>
    main()
  File "E:/workspace/code/GPT2-Chinese-master/generate.py", line 169, in main
    model = GPT2LMHeadModel.from_pretrained(args.model_path)
  File "D:\Anaconda3\lib\site-packages\transformers\modeling_utils.py", line 287, in from_pretrained
    **kwargs
  File "D:\Anaconda3\lib\site-packages\transformers\configuration_utils.py", line 154, in from_pretrained
    config = cls.from_json_file(resolved_config_file)
  File "D:\Anaconda3\lib\site-packages\transformers\configuration_utils.py", line 186, in from_json_file
    text = reader.read()
  File "D:\Anaconda3\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by Morizeyao** [comment]
读的是公布的预训练模型吗？

**Comment by ShengXiaoXiao** [comment]
> 请加一下微信讨论群，里面有预训练模型的作者hugh

恩 微信群加了 我联系下

**Comment by Morizeyao** [comment]
最终解决方案是：模型地址要指向目录而不是文件名。
